name: automatemr
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  # --- Heavy Scientific Binaries & C++ Extensions ---
  - cuda-nvcc
  - openmm
  - pdbfixer
  - kalign2
  - hhsuite
  - cctbx-base
  - pycuda
  - pip
  # --- Standard Python & Tricky Packages ---
  - pip:
      - nvidia-ml-py3
      - gemmi
      - mdtraj
      - polyleven
      - pandarallel
      - scikit-learn
      - hdbscan
      - colorama
      - biopython
      - psutil
      - --extra-index-url https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
      - jax[cuda12]==0.5.3
      - "colabfold[alphafold-minus-jax] @ git+https://github.com/sokrypton/ColabFold"
      - "colabfold[alphafold]"
      - gradio>=4.0.0
