name: automatemr
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - cuda-nvcc
  - openmm
  - pdbfixer
  - kalign2
  - hhsuite
  - cctbx-base
  - pycuda
  - nvidia-ml-py3
  - gemmi
  - mdtraj
  - polyleven
  - pandarallel
  - scikit-learn
  - hdbscan
  - colorama
  - biopython
  - psutil
  - pip
  - pip:
      - --extra-index-url https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
      - jax[cuda12]==0.5.3
      - "colabfold[alphafold-minus-jax] @ git+https://github.com/sokrypton/ColabFold"
      - "colabfold[alphafold]"
